# Downloading Market and Fundamental Data with `yfinance`

## Imports & Settings

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import yfinance as yf

## How to work with a Ticker object

In [6]:
symbol = 'META'
ticker = yf.Ticker(symbol)

### Show ticker info

In [7]:
pd.Series(ticker.info).head(20)

address1                                                        1 Meta Way
city                                                            Menlo Park
state                                                                   CA
zip                                                                  94025
country                                                      United States
phone                                                         650 543 4800
website                                        https://investor.atmeta.com
industry                                    Internet Content & Information
industryKey                                   internet-content-information
industryDisp                                Internet Content & Information
sector                                              Communication Services
sectorKey                                           communication-services
sectorDisp                                          Communication Services
longBusinessSummary      Meta Platforms, Inc. engages in the developmen...
fullTimeEmployees                                                    76834
companyOfficers          [{'maxAge': 1, 'name': 'Mr. Mark Elliot Zucker...
auditRisk                                                               10
boardRisk                                                               10
compensationRisk                                                        10
shareHolderRightsRisk                                                   10
dtype: object

### Get market data

In [8]:
data = ticker.history(period='5d',
                      interval='1m',
                      start=None,
                      end=None,
                      actions=True,
                      auto_adjust=True,
                      back_adjust=False)
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1946 entries, 2025-05-20 09:30:00-04:00 to 2025-05-27 15:59:00-04:00
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1946 non-null   float64
 1   High          1946 non-null   float64
 2   Low           1946 non-null   float64
 3   Close         1946 non-null   float64
 4   Volume        1946 non-null   int64
 5   Dividends     1946 non-null   float64
 6   Stock Splits  1946 non-null   float64
dtypes: float64(6), int64(1)
memory usage: 121.6 KB

### View company actions

In [9]:
# show actions (dividends, splits)
ticker.actions

                           Dividends  Stock Splits
Date
2024-02-21 00:00:00-05:00      0.500           0.0
2024-06-14 00:00:00-04:00      0.500           0.0
2024-09-16 00:00:00-04:00      0.500           0.0
2024-12-16 00:00:00-05:00      0.500           0.0
2025-03-14 00:00:00-04:00      0.525           0.0

In [10]:
ticker.dividends

Date
2024-02-21 00:00:00-05:00    0.500
2024-06-14 00:00:00-04:00    0.500
2024-09-16 00:00:00-04:00    0.500
2024-12-16 00:00:00-05:00    0.500
2025-03-14 00:00:00-04:00    0.525
Name: Dividends, dtype: float64

In [11]:
ticker.splits

Series([], Name: Stock Splits, dtype: float64)

### Annual and Quarterly Financial Statement Summary

In [12]:
ticker.financials

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Tax Effect Of Unusual Items,-81420000.0,-64416000.0,-15795000.0,-23380000.0,NaN
Tax Rate For Calcs,0.118,0.176,0.195,0.167,NaN
Normalized EBITDA,87566000000.0,59418000000.0,37771000000.0,55414000000.0,NaN
Total Unusual Items,-690000000.0,-366000000.0,-81000000.0,-140000000.0,NaN
Total Unusual Items Excluding Goodwill,-690000000.0,-366000000.0,-81000000.0,-140000000.0,NaN
Net Income From Continuing Operation Net Minority Interest,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Reconciled Depreciation,15498000000.0,11178000000.0,8686000000.0,7967000000.0,NaN
Reconciled Cost Of Revenue,30161000000.0,25959000000.0,25249000000.0,22649000000.0,NaN
EBITDA,86876000000.0,59052000000.0,37690000000.0,55274000000.0,NaN
EBIT,71378000000.0,47874000000.0,29004000000.0,47307000000.0,NaN
Net Interest Income,1973000000.0,1043000000.0,-44000000.0,671000000.0,NaN
Interest Expense,715000000.0,446000000.0,185000000.0,23000000.0,NaN
Interest Income,2517000000.0,1639000000.0,461000000.0,484000000.0,NaN
Normalized Income,62968580000.0,39399584000.0,23265205000.0,39486620000.0,NaN
Net Income From Continuing And Discontinued Operation,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Total Expenses,95121000000.0,88151000000.0,87665000000.0,71176000000.0,NaN
Total Operating Income As Reported,69380000000.0,46751000000.0,28944000000.0,46753000000.0,NaN
Diluted Average Shares,2614000000.0,2629000000.0,2702000000.0,2859000000.0,NaN
Basic Average Shares,2534000000.0,2574000000.0,2687000000.0,2815000000.0,NaN
Diluted EPS,23.86,14.87,8.59,13.77,NaN
Basic EPS,24.61,15.19,8.63,13.99,NaN
Diluted NI Availto Com Stockholders,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Net Income Common Stockholders,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Otherunder Preferred Stock Dividend,NaN,NaN,NaN,NaN,0.0
Net Income,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Net Income Including Noncontrolling Interests,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Net Income Continuous Operations,62360000000.0,39098000000.0,23200000000.0,39370000000.0,NaN
Tax Provision,8303000000.0,8330000000.0,5619000000.0,7914000000.0,NaN
Pretax Income,70663000000.0,47428000000.0,28819000000.0,47284000000.0,NaN
Other Income Expense,-690000000.0,-366000000.0,-81000000.0,-140000000.0,NaN
Other Non Operating Income Expenses,NaN,NaN,-320000000.0,210000000.0,-34000000.0
Special Income Charges,NaN,NaN,NaN,0.0,0.0
Gain On Sale Of Security,-690000000.0,-366000000.0,-81000000.0,-140000000.0,NaN
Net Non Operating Interest Income Expense,1973000000.0,1043000000.0,-44000000.0,671000000.0,NaN
Total Other Finance Cost,-171000000.0,150000000.0,320000000.0,-210000000.0,NaN
Interest Expense Non Operating,715000000.0,446000000.0,185000000.0,23000000.0,NaN
Interest Income Non Operating,2517000000.0,1639000000.0,461000000.0,484000000.0,NaN
Operating Income,69380000000.0,46751000000.0,28944000000.0,46753000000.0,NaN
Operating Expense,64960000000.0,62192000000.0,62416000000.0,48527000000.0,NaN
Research And Development,43873000000.0,38483000000.0,35338000000.0,24655000000.0,NaN
Selling General And Administration,21087000000.0,23709000000.0,27078000000.0,23872000000.0,NaN
Selling And Marketing Expense,11347000000.0,12301000000.0,15262000000.0,14043000000.0,NaN
General And Administrative Expense,9740000000.0,11408000000.0,11816000000.0,9829000000.0,NaN
Other Gand A,9740000000.0,11408000000.0,11816000000.0,9829000000.0,NaN
Gross Profit,134340000000.0,108943000000.0,91360000000.0,95280000000.0,NaN
Cost Of Revenue,30161000000.0,25959000000.0,25249000000.0,22649000000.0,NaN
Total Revenue,164501000000.0,134902000000.0,116609000000.0,117929000000.0,NaN
Operating Revenue,162779000000.0,133844000000.0,115801000000.0,117208000000.0,NaN

In [13]:
ticker.quarterly_financials

,2025-03-31,2024-12-31,2024-09-30,2024-06-30,2024-03-31
Tax Effect Of Unusual Items,20880000.0,-44365234.375,1320000.0,-18480000.0,-19240000.0
Tax Rate For Calcs,0.09,0.115234,0.12,0.11,0.13
Normalized EBITDA,22290000000.0,28648000000.0,22046000000.0,19039000000.0,17832000000.0
Total Unusual Items,232000000.0,-385000000.0,11000000.0,-168000000.0,-148000000.0
Total Unusual Items Excluding Goodwill,232000000.0,-385000000.0,11000000.0,-168000000.0,-148000000.0
Net Income From Continuing Operation Net Minority Interest,16644000000.0,20838000000.0,15688000000.0,13465000000.0,12369000000.0
Reconciled Depreciation,3900000000.0,4460000000.0,4027000000.0,3637000000.0,3374000000.0
Reconciled Cost Of Revenue,7572000000.0,8839000000.0,7375000000.0,7308000000.0,6640000000.0
EBITDA,22522000000.0,28263000000.0,22057000000.0,18871000000.0,17684000000.0
EBIT,18622000000.0,23803000000.0,18030000000.0,15234000000.0,14310000000.0
Net Interest Income,595000000.0,573000000.0,461000000.0,427000000.0,513000000.0
Interest Expense,240000000.0,251000000.0,208000000.0,128000000.0,127000000.0
Interest Income,658000000.0,731000000.0,661000000.0,540000000.0,585000000.0
Normalized Income,16432880000.0,21178634765.625,15678320000.0,13614520000.0,12497760000.0
Net Income From Continuing And Discontinued Operation,16644000000.0,20838000000.0,15688000000.0,13465000000.0,12369000000.0
Total Expenses,24759000000.0,25021000000.0,23239000000.0,24224000000.0,22637000000.0
Total Operating Income As Reported,17555000000.0,23364000000.0,17350000000.0,14847000000.0,13818000000.0
Diluted Average Shares,2590000000.0,2599000000.0,2600000000.0,2610000000.0,2625000000.0
Basic Average Shares,2527000000.0,2529000000.0,2529000000.0,2534000000.0,2545000000.0
Diluted EPS,6.43,8.02,6.03,5.16,4.71
Basic EPS,6.59,8.24,6.2,5.31,4.86
Diluted NI Availto Com Stockholders,16644000000.0,20838000000.0,15688000000.0,13465000000.0,12369000000.0
Net Income Common Stockholders,16644000000.0,20838000000.0,15688000000.0,13465000000.0,12369000000.0
Net Income,16644000000.0,20838000000.0,15688000000.0,13465000000.0,12369000000.0
Net Income Including Noncontrolling Interests,16644000000.0,20838000000.0,15688000000.0,13465000000.0,12369000000.0
Net Income Continuous Operations,16644000000.0,20838000000.0,15688000000.0,13465000000.0,12369000000.0
Tax Provision,1738000000.0,2714000000.0,2134000000.0,1641000000.0,1814000000.0
Pretax Income,18382000000.0,23552000000.0,17822000000.0,15106000000.0,14183000000.0
Other Income Expense,232000000.0,-385000000.0,11000000.0,-168000000.0,-148000000.0
Gain On Sale Of Security,232000000.0,-385000000.0,11000000.0,-168000000.0,-148000000.0
Net Non Operating Interest Income Expense,595000000.0,573000000.0,461000000.0,427000000.0,513000000.0
Total Other Finance Cost,-177000000.0,-93000000.0,-8000000.0,-15000000.0,-55000000.0
Interest Expense Non Operating,240000000.0,251000000.0,208000000.0,128000000.0,127000000.0
Interest Income Non Operating,658000000.0,731000000.0,661000000.0,540000000.0,585000000.0
Operating Income,17555000000.0,23364000000.0,17350000000.0,14847000000.0,13818000000.0
Operating Expense,17187000000.0,16182000000.0,15864000000.0,16916000000.0,15997000000.0
Research And Development,12150000000.0,12180000000.0,11177000000.0,10537000000.0,9978000000.0
Selling General And Administration,5037000000.0,4002000000.0,4687000000.0,6379000000.0,6019000000.0
Selling And Marketing Expense,2757000000.0,3240000000.0,2822000000.0,2721000000.0,2564000000.0
General And Administrative Expense,2280000000.0,762000000.0,1865000000.0,3658000000.0,3455000000.0
Other Gand A,2280000000.0,762000000.0,1865000000.0,3658000000.0,3455000000.0
Gross Profit,34742000000.0,39546000000.0,33214000000.0,31763000000.0,29815000000.0
Cost Of Revenue,7572000000.0,8839000000.0,7375000000.0,7308000000.0,6640000000.0
Total Revenue,42314000000.0,48385000000.0,40589000000.0,39071000000.0,36455000000.0
Operating Revenue,41804000000.0,47866000000.0,40155000000.0,38682000000.0,36075000000.0

### Annual and Quarterly Balance Sheet

In [14]:
ticker.balance_sheet

,2024-12-31,2023-12-31,2022-12-31,2021-12-31,2020-12-31
Treasury Shares Number,NaN,0.0,NaN,NaN,NaN
Ordinary Shares Number,2534487662.0,2561000000.0,2614000000.0,2741000000.0,NaN
Share Issued,2534487662.0,2561000000.0,2614000000.0,2741000000.0,NaN
Total Debt,49060000000.0,37234000000.0,26591000000.0,13873000000.0,NaN
Tangible Book Value,161068000000.0,131726000000.0,104510000000.0,105048000000.0,NaN
...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,77815000000.0,65403000000.0,40738000000.0,47998000000.0,NaN
Other Short Term Investments,33926000000.0,23541000000.0,26057000000.0,31397000000.0,NaN
Cash And Cash Equivalents,43889000000.0,41862000000.0,14681000000.0,16601000000.0,NaN
Cash Equivalents,36671000000.0,35597000000.0,8505000000.0,9293000000.0,NaN
Cash Financial,7218000000.0,6265000000.0,6176000000.0,7308000000.0,NaN

In [15]:
ticker.quarterly_balance_sheet

,2025-03-31,2024-12-31,2024-09-30,2024-06-30,2024-03-31,2023-12-31,2023-09-30
Treasury Shares Number,NaN,NaN,NaN,NaN,NaN,0.0,NaN
Ordinary Shares Number,2523000000.0,2534487662.0,2524000000.0,2533087958.0,2537000000.0,NaN,NaN
Share Issued,2523000000.0,2534487662.0,2524000000.0,2533087958.0,2537000000.0,NaN,NaN
Net Debt,79000000.0,NaN,NaN,NaN,NaN,NaN,NaN
Total Debt,49519000000.0,49060000000.0,49047000000.0,37991000000.0,37633000000.0,NaN,NaN
...,...,...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,70230000000.0,77815000000.0,70900000000.0,58080000000.0,58120000000.0,NaN,NaN
Other Short Term Investments,41480000000.0,33926000000.0,27048000000.0,26035000000.0,25813000000.0,NaN,NaN
Cash And Cash Equivalents,28750000000.0,43889000000.0,43852000000.0,32045000000.0,32307000000.0,NaN,NaN
Cash Equivalents,24588000000.0,36671000000.0,37323000000.0,25886000000.0,25812000000.0,NaN,NaN
Cash Financial,4162000000.0,7218000000.0,6529000000.0,6159000000.0,6495000000.0,NaN,NaN

### Annual and Quarterly Cashflow Statement

In [73]:
ticker.cashflow

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [74]:
ticker.quarterly_cashflow

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [75]:
ticker.earnings

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

In [76]:
ticker.quarterly_earnings

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

### Sustainability: Environmental, Social and Governance (ESG)

In [77]:
ticker.sustainability

                                     Value
2020-3
palmOil                              False
controversialWeapons                 False
gambling                             False
socialScore                          18.73
nuclear                              False
furLeather                           False
alcoholic                            False
gmo                                  False
catholic                             False
socialPercentile                         0
peerCount                              100
governanceScore                      12.41
environmentPercentile                    0
animalTesting                        False
tobacco                              False
totalEsg                             32.64
highestControversy                       4
esgPerformance                    OUT_PERF
coal                                 False
pesticides                           False
adult                                False
percentile                           63.64
peerGroup              Software & Services
smallArms                            False
environmentScore                      1.51
governancePercentile                     0
militaryContract                     False

### Analyst Recommendations

In [78]:
ticker.recommendations.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 457 entries, 2012-06-29 06:50:00 to 2020-05-21 14:11:46
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Firm        457 non-null    object
 1   To Grade    457 non-null    object
 2   From Grade  457 non-null    object
 3   Action      457 non-null    object
dtypes: object(4)
memory usage: 17.9+ KB

In [79]:
ticker.recommendations.tail(10)

                                           Firm    To Grade From Grade Action
Date
2020-04-30 12:45:08              Morgan Stanley  Overweight              main
2020-04-30 12:56:51                      Stifel         Buy              main
2020-04-30 13:07:11               Credit Suisse  Outperform              main
2020-04-30 13:22:50                 Oppenheimer  Outperform              main
2020-04-30 13:37:07                         UBS         Buy              main
2020-04-30 13:52:56             Nomura Instinet         Buy              main
2020-04-30 15:12:15                  Guggenheim         Buy              main
2020-04-30 16:13:15  SunTrust Robinson Humphrey         Buy              main
2020-04-30 16:39:15           Canaccord Genuity         Buy              main
2020-05-21 14:11:46                      Stifel         Buy              main

### Upcoming Events

In [80]:
ticker.calendar

                                    0                    1
Earnings Date     2020-07-22 00:00:00  2020-07-27 00:00:00
Earnings Average                 1.37                 1.37
Earnings Low                     0.97                 0.97
Earnings High                    1.71                 1.71
Revenue Average           17174200000          17174200000
Revenue Low               16156000000          16156000000
Revenue High              19018000000          19018000000

### Option Expiration Dates

In [81]:
ticker.options

('2020-06-18',
 '2020-06-25',
 '2020-07-01',
 '2020-07-09',
 '2020-07-16',
 '2020-07-23',
 '2020-07-30',
 '2020-08-20',
 '2020-09-17',
 '2020-11-19',
 '2020-12-17',
 '2021-01-14',
 '2021-03-18',
 '2021-06-17',
 '2022-01-20',
 '2022-06-16',
 '2022-09-15',
 '2026-02-20')

In [82]:
expiration = ticker.options[0]

In [83]:
options = ticker.option_chain(expiration)

In [84]:
options.calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   contractSymbol     71 non-null     object
 1   lastTradeDate      71 non-null     datetime64[ns]
 2   strike             71 non-null     float64
 3   lastPrice          71 non-null     float64
 4   bid                71 non-null     float64
 5   ask                71 non-null     float64
 6   change             71 non-null     float64
 7   percentChange      71 non-null     float64
 8   volume             71 non-null     int64
 9   openInterest       71 non-null     int64
 10  impliedVolatility  71 non-null     float64
 11  inTheMoney         71 non-null     bool
 12  contractSize       71 non-null     object
 13  currency           71 non-null     object
dtypes: bool(1), datetime64[ns](1), float64(7), int64(2), object(3)
memory usage: 7.4+ KB

In [85]:
options.calls.head()

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,FB200619C00070000,2020-06-16 14:59:51,70.0,163.70,165.80,166.1,1.599991,0.987039,1,7,0.00001,True,REGULAR,USD
1,FB200619C00075000,2020-06-10 13:30:00,75.0,165.90,160.80,161.1,0.000000,0.000000,1,12,0.00001,True,REGULAR,USD
2,FB200619C00080000,2020-06-15 19:59:00,80.0,151.90,155.80,156.1,0.000000,0.000000,5,172,0.00001,True,REGULAR,USD
3,FB200619C00085000,2020-06-09 14:45:07,85.0,152.77,150.25,151.0,0.000000,0.000000,15,33,0.00001,True,REGULAR,USD
4,FB200619C00090000,2020-06-09 13:41:05,90.0,144.35,145.35,146.3,0.000000,0.000000,2,24,0.00001,True,REGULAR,USD

In [86]:
options.puts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   contractSymbol     67 non-null     object
 1   lastTradeDate      67 non-null     datetime64[ns]
 2   strike             67 non-null     float64
 3   lastPrice          67 non-null     float64
 4   bid                67 non-null     float64
 5   ask                67 non-null     float64
 6   change             67 non-null     float64
 7   percentChange      67 non-null     float64
 8   volume             67 non-null     int64
 9   openInterest       67 non-null     int64
 10  impliedVolatility  67 non-null     float64
 11  inTheMoney         67 non-null     bool
 12  contractSize       67 non-null     object
 13  currency           67 non-null     object
dtypes: bool(1), datetime64[ns](1), float64(7), int64(2), object(3)
memory usage: 7.0+ KB

## Data Download with proxy server

You can use a proxy server to avoid having your IP blacklisted as illustrated below (but need an actual PROXY_SERVER).

In [27]:
PROXY_SERVER = 'PROXY_SERVER'

The following will only work with proper PROXY_SERVER...

In [28]:
# msft = yf.Ticker("MSFT")

# msft.history(proxy=PROXY_SERVER)
# msft.get_actions(proxy=PROXY_SERVER)
# msft.get_dividends(proxy=PROXY_SERVER)
# msft.get_splits(proxy=PROXY_SERVER)
# msft.get_balance_sheet(proxy=PROXY_SERVER)
# msft.get_cashflow(proxy=PROXY_SERVER)
# msgt.option_chain(proxy=PROXY_SERVER)

## Downloading multiple symbols

In [87]:
tickers = yf.Tickers('msft aapl goog')

In [88]:
tickers

yfinance.Tickers object <MSFT,AAPL,GOOG>

In [89]:
pd.Series(tickers.tickers.MSFT.info)

zip                                                                  98052
sector                                                          Technology
fullTimeEmployees                                                   144000
longBusinessSummary      Microsoft Corporation develops, licenses, and ...
city                                                               Redmond
                                               ...
sharesShortPriorMonth                                             47763253
category                                                              None
fiveYearAverageReturn                                                 None
regularMarketPrice                                                  192.89
logo_url                           https://logo.clearbit.com/microsoft.com
Length: 122, dtype: object

In [90]:
tickers.tickers.AAPL.history(period="1mo")

              Open    High     Low   Close    Volume  Dividends  Stock Splits
Date
2020-05-18  313.17  316.50  310.32  314.96  33843100          0             0
2020-05-19  315.03  318.52  313.01  313.14  25432400          0             0
2020-05-20  316.68  319.52  316.52  319.23  27876200          0             0
2020-05-21  318.66  320.89  315.87  316.85  25672200          0             0
2020-05-22  315.77  319.23  315.35  318.89  20450800          0             0
2020-05-26  323.50  324.24  316.50  316.73  31380500          0             0
2020-05-27  316.14  318.71  313.09  318.11  28236300          0             0
2020-05-28  316.77  323.44  315.63  318.25  33390200          0             0
2020-05-29  319.25  321.15  316.47  317.94  38399500          0             0
2020-06-01  317.75  322.35  317.21  321.85  20197800          0             0
2020-06-02  320.75  323.44  318.93  323.34  21910700          0             0
2020-06-03  324.66  326.20  322.30  325.12  26122800          0             0
2020-06-04  324.39  325.62  320.78  322.32  21890100          0             0
2020-06-05  323.35  331.75  323.23  331.50  34312600          0             0
2020-06-08  330.25  333.60  327.32  333.46  23913600          0             0
2020-06-09  332.14  345.61  332.01  343.99  36928100          0             0
2020-06-10  347.90  354.77  346.09  352.84  41662900          0             0
2020-06-11  349.31  351.06  335.48  335.90  50415600          0             0
2020-06-12  344.72  347.80  334.22  338.80  50001500          0             0
2020-06-15  333.25  345.68  332.58  342.99  34642900          0             0
2020-06-16  351.46  353.02  344.72  351.71  23023184          0             0

In [91]:
tickers.history(period='1mo').stack(-1)

[*********************100%***********************]  3 of 3 completed

                       Close  Dividends         High          Low  \
Date
2020-05-18 AAPL   314.959991        0.0   316.500000   310.320007
           GOOG  1383.939941        0.0  1392.324951  1354.250000
           MSFT   184.396439        0.0   185.682849   183.449080
2020-05-19 AAPL   313.140015        0.0   318.519989   313.010010
           GOOG  1373.484985        0.0  1392.000000  1373.484985
...                      ...        ...          ...          ...
2020-06-15 GOOG  1419.849976        0.0  1424.800049  1387.920044
           MSFT   188.940002        0.0   190.820007   184.009995
2020-06-16 AAPL   351.709991        0.0   353.020111   344.720001
           GOOG  1444.350098        0.0  1455.020020  1425.900146
           MSFT   193.929993        0.0   195.580002   191.475006

                        Open  Stock Splits    Volume
Date
2020-05-18 AAPL   313.170013             0  33843100
           GOOG  1361.750000             0   1824000
           MSFT   185.234102             0  35306600
2020-05-19 AAPL   315.029999             0  25432400
           GOOG  1386.996948             0   1280600
...                      ...           ...       ...
2020-06-15 GOOG  1390.800049             0   1503900
           MSFT   184.580002             0  32712500
2020-06-16 AAPL   351.459991             0  23023184
           GOOG  1445.219971             0    840528
           MSFT   192.889999             0  21810226

[63 rows x 7 columns]

In [92]:
data = yf.download("SPY AAPL", start="2020-01-01", end="2020-01-05")

[*********************100%***********************]  2 of 2 completed

In [93]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2 entries, 2020-01-02 to 2020-01-03
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   (Adj Close, AAPL)  2 non-null      float64
 1   (Adj Close, SPY)   2 non-null      float64
 2   (Close, AAPL)      2 non-null      float64
 3   (Close, SPY)       2 non-null      float64
 4   (High, AAPL)       2 non-null      float64
 5   (High, SPY)        2 non-null      float64
 6   (Low, AAPL)        2 non-null      float64
 7   (Low, SPY)         2 non-null      float64
 8   (Open, AAPL)       2 non-null      float64
 9   (Open, SPY)        2 non-null      float64
 10  (Volume, AAPL)     2 non-null      int64
 11  (Volume, SPY)      2 non-null      int64
dtypes: float64(10), int64(2)
memory usage: 208.0 bytes

In [94]:
data = yf.download(
        tickers = "SPY AAPL MSFT", # list or string

        # use "period" instead of start/end
        # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        # (optional, default is '1mo')
        period = "5d",

        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "1m",

        # group by ticker (to access via data['SPY'])
        # (optional, default is 'column')
        group_by = 'ticker',

        # adjust all OHLC automatically
        # (optional, default is False)
        auto_adjust = True,

        # download pre/post regular market hours data
        # (optional, default is False)
        prepost = True,

        # use threads for mass downloading? (True/False/Integer)
        # (optional, default is True)
        threads = True,

        # proxy URL scheme use use when downloading?
        # (optional, default is None)
        proxy = None
    )

[*********************100%***********************]  3 of 3 completed

In [95]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4284 entries, 2020-06-10 04:00:00-04:00 to 2020-06-16 12:44:17-04:00
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (MSFT, Open)    3101 non-null   float64
 1   (MSFT, High)    3101 non-null   float64
 2   (MSFT, Low)     3101 non-null   float64
 3   (MSFT, Close)   3101 non-null   float64
 4   (MSFT, Volume)  3101 non-null   float64
 5   (AAPL, Open)    3287 non-null   float64
 6   (AAPL, High)    3287 non-null   float64
 7   (AAPL, Low)     3287 non-null   float64
 8   (AAPL, Close)   3287 non-null   float64
 9   (AAPL, Volume)  3287 non-null   float64
 10  (SPY, Open)     4125 non-null   float64
 11  (SPY, High)     4125 non-null   float64
 12  (SPY, Low)      4125 non-null   float64
 13  (SPY, Close)    4125 non-null   float64
 14  (SPY, Volume)   4125 non-null   float64
dtypes: float64(15)
memory usage: 535.5 KB

In [96]:
from pandas_datareader import data as pdr

import yfinance as yf
yf.pdr_override()

# download dataframe
data = pdr.get_data_yahoo('SPY',
                          start='2017-01-01',
                          end='2019-04-30',
                          auto_adjust=False)

[*********************100%***********************]  1 of 1 completed

In [97]:
# auto_adjust = True
data.tail()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2019-04-23,290.679993,293.140015,290.420013,292.880005,287.015472,52246600
2019-04-24,292.790009,293.160004,292.070007,292.230011,286.378540,50392900
2019-04-25,292.119995,292.779999,290.730011,292.049988,286.202118,57770900
2019-04-26,292.100006,293.489990,291.239990,293.410004,287.534882,50916400
2019-04-29,293.510010,294.450012,293.410004,293.869995,287.985657,57197700

In [98]:
# auto_adjust = False
data.tail()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2019-04-23,290.679993,293.140015,290.420013,292.880005,287.015472,52246600
2019-04-24,292.790009,293.160004,292.070007,292.230011,286.378540,50392900
2019-04-25,292.119995,292.779999,290.730011,292.049988,286.202118,57770900
2019-04-26,292.100006,293.489990,291.239990,293.410004,287.534882,50916400
2019-04-29,293.510010,294.450012,293.410004,293.869995,287.985657,57197700